# Alembic configuration file.
# See https://alembic.sqlalchemy.org/en/latest/tutorial.html

[alembic]
# Path to migration scripts, relative to this file's location
script_location = alembic

# Template string used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Timezone to use when rendering the date in the migration file name
timezone = UTC

# max length of characters to apply to the "slug" field
truncate_slug_length = 40

# Set to 'true' to run the environment during the 'revision' command,
# even when revision is created with --autogenerate
# revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without a source .py file
# to be detected as revisions in the versions/ directory
# sourceless = false

# Version path separator; As mentioned above, this is the character used to split
# version_locations. The default within new alembic.ini files is "os", which uses
# os.pathsep. If this key is omitted entirely, a legacy behavior is assumed, which
# is to treat the separator as a space, then as a colon.
version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# set to 'true' to search source files recursively in "version_locations"
# new in Alembic version 1.10
# recursive_version_locations = false

# the output encoding used when revision files are written from script.py.mako
output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://regnav:regnav@localhost:5432/regnav


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# format using "ruff" - check for linting errors, then reformat
# hooks = ruff-check, ruff-format
# ruff-check.type = console_scripts
# ruff-check.entrypoint = ruff
# ruff-check.options = check REVISION_SCRIPT_FILENAME --fix
# ruff-format.type = console_scripts
# ruff-format.entrypoint = ruff
# ruff-format.options = format REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
